# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-26 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='board',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='starter',
            new_name='creator',
        ),
    ]
